### ISSUE TITLE
Copyrights on leaks

### ISSUE THREAD

**Issue by Xiloe** [fir3z/Fortnite-Cheat-Stuff#2]
Ok so, idfk who is this guy who leaked Predator src, I'm the dev of it and I self leaked it on MDMA server lol, gime credits at least. :octocat:

**Comment by NeoxPublic** [comment]
GIVE ME CREDIT IT WAS MY SERVER THAT IT WAS LEAKED ON

**Comment by ThonkPT** [comment]
to the kids above eat cock kthx

**Comment by Xiloe** [comment]
STFU AND GIVE ME MY RIGHTS

**Comment by fir3z** [comment]
i cant verify that so sorry lmao
